# Generated by Django 4.0.6 on 2022-08-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=15)),
                ('savings', models.IntegerField(default=False)),
                ('destination', models.CharField(blank=True, max_length=15)),
                ('account_number', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField(default=False)),
                ('nationality', models.CharField(blank=True, max_length=15)),
                ('id_number', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('profile_picture', models.ImageField(default=False, upload_to='')),
                ('marital_status', models.CharField(blank=True, max_length=15)),
                ('signature', models.ImageField(default=False, upload_to='')),
                ('employment_status', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('pin', models.SmallIntegerField(blank=True)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(null=True)),
                ('customer', models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(blank=True, default=False, max_length=15)),
                ('transaction_code', models.CharField(blank=True, default=False, max_length=15)),
                ('charge', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default=False, max_length=15)),
                ('customer', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('origin_account', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_Receipt', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('transaction_cost', models.IntegerField(default=False)),
                ('active', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=False)),
                ('date', models.DateTimeField(null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('receipt_file', models.FileField(upload_to='')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField()),
                ('icon', models.ImageField(default=False, upload_to='')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, max_length=15)),
                ('amount', models.IntegerField(default=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('loan_terms', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateTimeField(null=True)),
                ('guarantor', models.CharField(blank=True, max_length=15)),
                ('balance', models.IntegerField(default=False)),
                ('duration', models.CharField(blank=True, max_length=15)),
                ('interest', models.IntegerField(default=False)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(null=True)),
                ('card_status', models.CharField(blank=True, max_length=18)),
                ('security_code', models.IntegerField(default=False)),
                ('signature', models.ImageField(default=True, upload_to='')),
                ('issuer', models.CharField(blank=True, max_length=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
