# Generated by Django 4.0.6 on 2022-08-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_customer_email_customer_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True)),
                ('pin', models.SmallIntegerField(blank=True)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
    ]
