# Generated by Django 4.0.6 on 2022-08-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_amount_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
