# Generated by Django 4.0.6 on 2022-08-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_customer_employment_status_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=15)),
                ('savings', models.IntegerField(default=False)),
                ('destination', models.CharField(blank=True, max_length=15)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
