# Generated by Django 4.0.6 on 2022-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_card_card_name_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipts',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipts',
            name='receipt_type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
