# Generated by Django 4.0.6 on 2022-08-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_receipts_amount_receipts_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='third_party',
            old_name='full_name',
            new_name='party_name',
        ),
    ]
