# Generated by Django 4.0.6 on 2022-08-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(null=True)),
                ('card_status', models.CharField(blank=True, max_length=18)),
                ('security_code', models.IntegerField(default=False)),
                ('signature', models.ImageField(default=True, upload_to='')),
                ('issuer', models.CharField(blank=True, max_length=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
    ]
