# Generated by Django 4.0.6 on 2022-08-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_rename_full_name_third_party_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='destination',
        ),
    ]
