# Generated by Django 4.0.6 on 2022-08-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, max_length=15)),
                ('amount', models.IntegerField(default=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('loan_terms', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateTimeField(null=True)),
                ('guarantor', models.CharField(blank=True, max_length=15)),
                ('balance', models.IntegerField(default=False)),
                ('duration', models.CharField(blank=True, max_length=15)),
                ('interest', models.IntegerField(default=False)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
